### ISSUE TITLE
User's email is not fetched

### ISSUE THREAD

**Issue by JustMikey** [sobolevn/ueberauth_vk#1]
The user's email is passed along side with the token, not in the response from `users.get` API request thus it doesn't get set in the `info` callback.

**Comment by sobolevn** [comment]
Have a look at this line: https://github.com/sobolevn/ueberauth_vk/commit/542eb8b452a5339b6026f2b966a5d11d0080424f#diff-d24abdb76a99200e713f22e8cf64ae4bL6

I have changed the default scope.

**Comment by JustMikey** [comment]
Everything works like a charm now. Thank you :) You should probably bumb the version.
