### ISSUE TITLE
Unlock oauth2

### ISSUE THREAD

**Issue by JustMikey** [sobolevn/ueberauth_vk#13]
There is a new `0.8.*` version of `oauth2` which is used by `ueberauth_facebook` and probably the others and probably should be used by us. I have a feeling there is no need to strong lock the package to the `0.6` version anymore.

**Comment by sobolevn** [comment]
Tried to change it to `~> 0.8`, now tests do not pass.

> 
> Generated ueberauth_vk app
> .
> 
>   1) test default callback phase (Ueberauth.Strategy.VKTest)
>      test/ueberauth/strategy/vk_test.exs:58
>      ** (ArgumentError) argument error
>      stacktrace:
>        :erlang.iolist_to_binary(#Reference<0.0.2.771>)
>        lib/poison/parser.ex:35: Poison.Parser.parse/2
>        lib/poison/parser.ex:51: Poison.Parser.parse!/2
>        lib/poison.ex:83: Poison.decode!/2
>        (oauth2) lib/oauth2/response.ex:32: OAuth2.Response.new/3
>        (oauth2) lib/oauth2/request.ex:23: OAuth2.Request.request/6
>        (oauth2) lib/oauth2/client.ex:216: OAuth2.Client.get_token/4
>        (oauth2) lib/oauth2/client.ex:231: OAuth2.Client.get_token!/4
>        (ueberauth_vk) lib/ueberauth/strategy/vk.ex:47: Ueberauth.Strategy.VK.handle_callback!/1
>        (ueberauth) lib/ueberauth/strategy.ex:299: Ueberauth.Strategy.run_callback/2
>        test/test_helper.exs:1: SpecRouter.plug_builder_call/2
>        test/ueberauth/strategy/vk_test.exs:65: (test)
> 
> ..
> 
> Finished in 0.3 seconds
> 4 tests, 1 failure
