### ISSUE TITLE
release on hex

### ISSUE THREAD

**Issue by kelostrada** [sobolevn/ueberauth_vk#17]
Please create a release on hex for 0.2.1

**Comment by sobolevn** [comment]
Published: https://hex.pm/packages/ueberauth_vk

Please report any issues, if you ever find ones.

**Comment by sobolevn** [comment]
I have actually released `v0.2.2`. I had issues with docs on the previous release.
See [CHANGELOG](https://github.com/sobolevn/ueberauth_vk/blob/master/CHANGELOG.md).
