### ISSUE TITLE
Problems with OAuth2

### ISSUE THREAD

**Issue by JustMikey** [sobolevn/ueberauth_vk#9]
OAuth2 package has some backwards incompatible changes after version `0.7` which break this package. We gotta handle it somehow. The OAuth2 changelog can be found [here](https://github.com/scrogson/oauth2/blob/master/CHANGELOG.md)

**Comment by sobolevn** [comment]
Thanks for the feedback! Got it.

**Comment by sobolevn** [comment]
Have you found any solutions to this problem?

**Comment by JustMikey** [comment]
I didn't really search to be honest, as far as I understand the OAuth2 has just changed the interface and we need to just use that new one.
